In [1]:
# baseado em https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
# https://www.codigofluente.com.br/aula-06-scikit-learn-vizinhos-mais-proximos-knn/
# https://colab.research.google.com/github/littlecolumns/ds4j-notebooks/blob/master/classification/notebooks/Correcting%20for%20imbalanced%20datasets.ipynb#scrollTo=jq9376MGvTa7

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import cluster, neighbors, svm, metrics, preprocessing
import math

In [3]:
df = pd.read_csv('winequalityN.csv', encoding = "ISO-8859-1")

In [4]:
df = df.iloc[:, 1:].values
df = df[~np.isnan(df).any(axis=1)]

In [5]:
X = df[:, :-1]
y = df[:, 11]

In [6]:
# unbalanced : 					0.59
# train oversampled: 				0.57-0.59
# train undersampled: 				0.12-0.18
# test oversampled: 				0.34-0.37-0.47
# test undersampled: 				0.29-0.43
# train + test oversampled: 			0.32-0.44
# train + test undersampled: 			0.08-0.13-0.19
# train undersampled + test oversampled:	0.12-0.17
# train oversampled + test undersampled:	0.43-0.56
# db oversampled:				0.90-0.91
# db undersampled:				0.14-0.29

from imblearn.over_sampling import RandomOverSampler

OverResampler = RandomOverSampler()

X, y = OverResampler.fit_resample(X, y)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [8]:
# n_neighbors=1: macro avg       0.90      0.91      0.90
# n_neighbors=2: macro avg       0.86      0.86      0.86
# n_neighbors=3: macro avg       0.83      0.84      0.83
# n_neighbors=4: macro avg       0.81      0.82      0.81
# n_neighbors=5: macro avg       0.80      0.81      0.8

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [9]:
y_pred = classifier.predict(X_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[535   0   0   0   0   0   0]
 [  0 569   0   0   0   0   0]
 [  3  20 466  85  26   2   0]
 [  1   8 128 354  79  14   0]
 [  0   3   4  16 525   2   0]
 [  0   0   0   0   0 540   0]
 [  0   0   0   0   0   0 568]]
              precision    recall  f1-score   support

         3.0       0.99      1.00      1.00       535
         4.0       0.95      1.00      0.97       569
         5.0       0.78      0.77      0.78       602
         6.0       0.78      0.61      0.68       584
         7.0       0.83      0.95      0.89       550
         8.0       0.97      1.00      0.98       540
         9.0       1.00      1.00      1.00       568

    accuracy                           0.90      3948
   macro avg       0.90      0.90      0.90      3948
weighted avg       0.90      0.90      0.90      3948

