In [1]:
# baseado em https://stackabuse.com/k-nearest-neighbors-algorithm-in-python-and-scikit-learn/
# https://www.codigofluente.com.br/aula-06-scikit-learn-vizinhos-mais-proximos-knn/
# https://colab.research.google.com/github/littlecolumns/ds4j-notebooks/blob/master/classification/notebooks/Correcting%20for%20imbalanced%20datasets.ipynb#scrollTo=jq9376MGvTa7

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import cluster, neighbors, svm, metrics, preprocessing
import math
np.set_printoptions(suppress=True)

In [3]:
df = pd.read_csv('penguins_size.csv', encoding = "ISO-8859-1")

In [4]:
# Import label encoder
from sklearn import preprocessing
 
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
 
# Encode labels in column 'species'.
df['species']= label_encoder.fit_transform(df['species'])
df['island']= label_encoder.fit_transform(df['island'])
df['sex']= label_encoder.fit_transform(df['sex'])

In [5]:
# df = df.iloc[:, 1:].values
df = df[~np.isnan(df).any(axis=1)]
df = df.to_numpy()

In [6]:
y = df[:, :1]
X = df[:, 1:]

In [7]:
# db oversampled:        macro avg       0.92      0.92      0.92
# db undersampled:		 macro avg       0.62      0.63      0.6

from imblearn.over_sampling import RandomOverSampler

OverResampler = RandomOverSampler()

X, y = OverResampler.fit_resample(X, y)

In [8]:
from sklearn.preprocessing import StandardScaler

X = StandardScaler().fit_transform(X) 

df = pd.DataFrame(X, columns = ['island','culmen_length_mm','culmen_depth_mm', 'flipper_length_mm', 'body_mass_g', 'sex'])
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [10]:
# n_neighbors=1: macro avg       0.92      0.92      0.92
# n_neighbors=2: macro avg       0.87      0.87      0.87
# n_neighbors=3: macro avg       0.89      0.88      0.87
# n_neighbors=4: macro avg       0.84      0.84      0.8
# n_neighbors=5: macro avg       0.78      0.80      0.78

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [11]:
y_pred = classifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[34  0  0]
 [ 0 30  0]
 [ 0  0 27]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        34
         1.0       1.00      1.00      1.00        30
         2.0       1.00      1.00      1.00        27

    accuracy                           1.00        91
   macro avg       1.00      1.00      1.00        91
weighted avg       1.00      1.00      1.00        91

